(******************************************************************************)
(*                                                                            *)
(*               Battle of Stamford Bridge: Tactical Chronology               *)
(*                                                                            *)
(*     Formalizes the engagement of 25 September 1066: Harold Godwinson's     *)
(*     forced march from London, Norwegian army disposition across the        *)
(*     River Derwent, bridge chokepoint defense, and rout of Harald           *)
(*     Hardrada's forces. Proves timeline constraints on the Hastings march.  *)
(*                                                                            *)
(*     "Seven feet of English ground, or as much more as he is taller than    *)
(*     other men."                                                            *)
(*     - Harold Godwinson's offer to Harald Hardrada, 1066                    *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
